### ISSUE TITLE
Frontend User Personal Schedule Part 1 - Navbar and Placeholder Page

### ISSUE THREAD

**Issue by ScottUCSB** [ucsb-cs156-w22/team04-w22-5pm-courses#24]
Add PersonalSchedules menu and page placeholders

The menu shows up only when logged in.  It has only two items for Users (List and Create). These links go to placeholder pages PersonalSchedulesIndexPage and PersonalSchedulesCreatePage.

You can use the menu for Todos and the placeholder pages for Todos (already in the repo) as models.(Team03)

# Navbar related Acceptance Criteria

- [x] There is a menu item PersonalSchedules (this is done on the Navbar)
- [x] The menu item on the navbar only shows up when you are logged in.
- [x] It has two items for Users, List and Create
- [x] List routes to  `/personalschedules/list`
- [x] Create routes to  `/personalschedules/create`

# Page related acceptance criteria

- [x] There are pages components under `/frontend/src/main/pages/PersonalSchedules/` similar to those under `/frontend/src/main/pages/Todos/` for the create and index pages.
- [x] There are entries for these pages in the storybook.
- [x] The List placeholder page is available at `/personalschedules/list` (this is done in `App.js`)
- [x] The Create placeholder page is available at `/personalschedules/create` (this is done in `App.js`)

# Passing Criteria
- [x] There is 100% test coverage from `npm run coverage`
- [x] There is 100% test coverage from `npx stryker run`

**Comment by tiny-babies** [comment]
Sorry I have been taking a long minute to finish this.  My branch is at https://github.com/ucsb-cs156-w22/team04-w22-5pm-courses/tree/nj-team02-personalSchedules-placeholders or "nj-team02-personalSchedules-placeholders" for anyone who needs to finish this issue in case it is blocking.
