### ISSUE TITLE
Frontend User Personal Schedule Part 1.2 - Form Component

### ISSUE THREAD

**Issue by ScottUCSB** [ucsb-cs156-w22/team04-w22-5pm-courses#26]
Make a form for PersonalSchedule to allow data entry

Model your form after UCSBDateForm from team03

- [x] There is a form component under `frontend/src/main/components/PersonalSchedules/PersonalSchedulesForm
- [x]  That component has appropriate fields that match those in the database table
- [x] There is data validation appropriate to the various fields
- [x] There is a storybook entry that shows how the form works.
- [x] There is 100% test coverage from npm run coverage
- [x] There is 100% test coverage from npm run coverage and npx stryker run

**Comment by tiny-babies** [comment]
At the time of this PR Comment, PersonalSchedules Entities and Repository has not been merged into main. Some of the variables in this PR are dependent on how they are defined in Personal Schedules Entities, so this may need to be addressed later if issues arise after PersonalSchedules Entities is merged into main.
